### ISSUE TITLE
Source Code For Duden & OCR+ Workflows

### ISSUE THREAD

**Issue by RomanBoegli** [zeitlings/alfred-workflows#10]
Hi @zeitlings 
Thanks for sharing these great workflows in your repo.
May I ask if you plan to open-source the Duden & OCR+ code in near future?

**Comment by zeitlings** [comment]
Hey @RomanBoegli, not really. Both of the workflow sources are pretty much playgrounds and columbaria for experiments that need serious refactoring and cosmetic tweaking to become presentable 😄. Especially the OCR+ project. The source code for the Duden workflow documents my becoming familiar with the requirements of Alfred's script filter, and thus I consider it to be quite outdated from today's POV. The heavy lifting, however, is done by [SwiftSoup](https://github.com/scinfu/SwiftSoup). I may consider it should I find the time and muse to revisit the projects, but no promises.
