### ISSUE TITLE
What is this character in the script?

### ISSUE THREAD

**Issue by Sponge-bink** [zeitlings/alfred-workflows#12]
<img width="725" alt="Screenshot 2024-06-14 at 2 13 56 PM" src="https://github.com/zeitlings/alfred-workflows/assets/33798984/7505077c-f726-44c2-af9f-ba22c35ad86d">

<img width="947" alt="image" src="https://github.com/zeitlings/alfred-workflows/assets/33798984/4d55b98e-f214-4289-869b-85041614841d">

<img width="745" alt="image" src="https://github.com/zeitlings/alfred-workflows/assets/33798984/0950cb19-670f-469c-bfa6-2e0845fb5f0c">

**Comment by zeitlings** [comment]
Hey @Sponge-bink, that's an [SF Symbol](https://developer.apple.com/sf-symbols/) glyph representing the battery case. If you install Apple's [SF Pro](https://developer.apple.com/fonts/) font, you should be able to see it.
