### ISSUE TITLE
Can I change the save shortcut to Command+S?

### ISSUE THREAD

**Issue by huangzhichengjiaosuo** [zeitlings/alfred-workflows#16]
Command+S is normal Save Action shortcut,I've gotten used to using this shortcut, can I change it?

**Comment by zeitlings** [comment]
Hey @huangzhichengjiaosuo 
What are you referring to? 
In general, this is a limitation imposed by Alfred and not something that can be changed within a workflow.
You may want to suggest it as a feature request for the application at https://www.alfredforum.com/
