### ISSUE TITLE
CP - Hex value is incorrect. 00 shortened to 0

### ISSUE THREAD

**Issue by daves-flutterint** [zeitlings/alfred-workflows#17]
Here is my example
<img width="736" alt="image" src="https://github.com/zeitlings/alfred-workflows/assets/137533984/e5afad9e-be56-4cf0-8c71-09141a13dce7">

**Comment by persimmonsoft** [comment]
Would something like:
`String(format:"#%02X%02X%02X", red, green, blue)`
be better for formatting it?
I am not a Swift dev, so I am just speculating

**Comment by persimmonsoft** [comment]
Created PR for fix

**Comment by zeitlings** [comment]
Hey @persimmonsoft 
Thanks, I'm traveling right now, but I'll have a look at it when I get the chance.

**Comment by zeitlings** [comment]
> `String(format:"#%02X%02X%02X", red, green, blue)`

This should work fine! I'm not a big fan of this kind of string formatting, though (at least in Swift).
Anyway, thanks again @daves-flutterint ! The issue should be fixed now: https://github.com/zeitlings/alfred-workflows/commit/48e4234aa246d172b8000cc753b2d3e96e83b431
