### ISSUE TITLE
New File: Bug: If ⌘↩ is first ever choice, cache never builds

### ISSUE THREAD

**Issue by vitorgalvao** [zeitlings/alfred-workflows#19]
In New File 1.2.0, reset the workflow:

1. Delete `/Users/vitor/Library/Application Support/Alfred/Workflow Data/com.zeitlings.mkfile`.
2. Set `cached` Workflow Environment Variable to `0`.

Then, type `new` and do <kbd>⌘</kbd><kbd>↩</kbd>. Because this bypasses the Run Script that calls the External Trigger to build the cache, what the user sees is a permanent message saying it’s building the cache, but it will never finish because it never started.

**Comment by zeitlings** [comment]
Thanks! I'll take a look at it.

**Comment by zeitlings** [comment]
Fixed with [v1.3.0-nf](https://github.com/zeitlings/alfred-workflows/releases/tag/v1.3.0-nf).
