### ISSUE TITLE
The OCR workflow not working

### ISSUE THREAD

**Issue by saeedesmaili** [zeitlings/alfred-workflows#2]
Hi
I have installed and tried the OCR workflow, but it doesn't seem to be working. Is installing the workflow enough or should I download the `AlfredOCR.swift` file and put it somewhere as well? If yes, where? 
I'm using MacOS 13.2.1 and Alfred 5.

The Mac asked me to grant screen recording access to Alfred when I ran the workflow for the first time, and I approved.
Here is the output of the workflow log:
<img width="653" alt="image" src="https://user-images.githubusercontent.com/13351748/223725076-0f3491d7-dda0-4a60-bf10-c5bc10917089.png">

**Comment by saeedesmaili** [comment]
Apparently the screen recording access wasn't granted for some reason.
A minor improvement could be if workflow alerted again if the access wasn't granted.

**Comment by zeitlings** [comment]
Hey @saeedesmaili, screen recording permissions are a MacOS and Alfred thing, the workflow doesn't explicitly check for that. But I'm glad you got it working.
