### ISSUE TITLE
Feature Window Navigator: List hidden apps

### ISSUE THREAD

**Issue by zap0xfce2** [zeitlings/alfred-workflows#22]
Is it possible to list hidden apps witch i hid with cmd+h?
Currently when i hide an app with cmd+h it will not show in the list :(

**Comment by zeitlings** [comment]
Hey @zap0xfce2 

I'm not currently aware of a way to catch windows of hidden apps. They obviously cannot be found on any desktop space. 
This behavior aligns with the purpose of the workflow. However, I'll keep an eye open and reconsider the feature request if a feasible solution presents itself.
