### ISSUE TITLE
Why Alfred's snippets fail on the Scratchpad?

### ISSUE THREAD

**Issue by DesBw** [zeitlings/alfred-workflows#26]
I not able to use the Alfred's snippets on the scratchpad. 
 I want to day-stamp my notes. Is there anyway to enable that?

**Comment by zeitlings** [comment]
Hey @DesBw 
When extending a snippet, Alfred stops focusing on the workflow and tends to the snippet expansion instead. 
Trying to extend a snippet in the scratchpad, or within any workflow, attempts some kind of Alfred-ception which unfortunately doesn't work. If you would like that to be possible, you should bring it to the attention of the developers at the [Alfred Forum](https://www.alfredforum.com/).
