### ISSUE TITLE
"New File" workflow not working correctly during fallback

### ISSUE THREAD

**Issue by kennguyen107** [zeitlings/alfred-workflows#27]
When triggering "New File" workflow without having Finder open, the name of the fallback folder gets prepended to the new file, and the new file is created into the root folder instead of the designated fallback folder. Apparently, this only happens when I choose "Downloads" folder as fallback. When choosing other folders as fallback, the file is created in the parent folder of the designated fallback folder instead.

I believe that the last "/" character might not be included when the workflow is run.

**Comment by zeitlings** [comment]
Hi @kennguyen107 

> I believe that the last "/" character might not be included when the workflow is run.

Yep, the solidus was missing. Will be fixed soon. Thanks for reporting!
