### ISSUE TITLE
I wonder if you can add Logitech product information. Also, the battery icon is abnormally displayed as shown in the picture

### ISSUE THREAD

**Issue by circumeo** [zeitlings/alfred-workflows#5]
Logitec MX Anywhere 3 Mac:
              Address: FC:83:04:CE:25:2C
              Vendor ID: 0x046D
              Product ID: 0xB025
              Firmware Version: MPM24.01_0015
              Minor Type: Mouse
              Services: 0x400000 < BLE >

          Logitec Keyboard K380:
              Address: F4:73:35:7E:43:EE
              Vendor ID: 0x046D
              Product ID: 0xB342
              Firmware Version: 66.0.1
              Minor Type: Keyboard

         AirPods:
              Address: 40:26:19:D5:DA:67
              Vendor ID: 0x004C
              Product ID: 0x2002
              Firmware Version: 6.8.8
              Minor Type: Headphones

         AirPods Pro:
              Address: 44:F0:9E:50:6C:AF
              Vendor ID: 0x004C
              Product ID: 0x200E
              Case Version: 1.3.9
              Firmware Version: 5​E133

<img width="1410" alt="screenshot_2023-05-04_17-36-08" src="https://user-images.githubusercontent.com/76243664/236153032-03ceaf0a-4299-4f2d-b5d7-ec4d69c96afc.png">
<img width="778" alt="스크린샷 2023-05-04 오후 5 38 30" src="https://user-images.githubusercontent.com/76243664/236153514-ca02992e-7e57-4ac7-ac14-affc649f81bf.png">

**Comment by zeitlings** [comment]
Hey @circumeo 
There is no information about the _Battery Level_ for the Logitech products judging from your log, unfortunately.
As for the symbols, you may need to set your theme to use the system font (SF Pro) if Alfred doesn't fall back on it by default. I would assume that SF Pro comes with macOS by default these days, but just in case: 
- https://developer.apple.com/fonts/
- https://developer.apple.com/sf-symbols/

**Comment by circumeo** [comment]
> 
Thank you for the comment :)
Don't you have any plans to add Logitech products through future updates?

**Comment by zeitlings** [comment]
Hey, sure, I'd love to, but it seems that Apple may have access to proprietary information that third-party manufacturers don't share with the general public, which is why the battery level shows up in the Bluetooth settings, but is not available via `ioreg` or `system_profiler`. If there is a way to get this information, I'll be happy to add it 😄

And if you know a way, let me know!

**Comment by circumeo** [comment]
> Hey, sure, I'd love to, but it seems that Apple may have access to proprietary information that third-party manufacturers don't share with the general public, which is why the battery level shows up in the Bluetooth settings, but is not available via `ioreg` or `system_profiler`. If there is a way to get this information, I'll be happy to add it 😄
> 
> And if you know a way, let me know!

I'm sorry I didn't help you 🥹
I hope you find a way one day!
