### ISSUE TITLE
OCR Light not work on macOS 14.1

### ISSUE THREAD

**Issue by ivanberry** [zeitlings/alfred-workflows#8]
### debug log

[15:42:24.926] Logging Started...
[15:42:32.351] OCR[[Hotkey](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.FB3F1227-E1E4-485F-AE7D-090E781D5B39%3E11730831-84BC-453A-8A40-24C268C4CDEB)] Processing complete
[15:42:32.362] OCR[[Hotkey](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.FB3F1227-E1E4-485F-AE7D-090E781D5B39%3E11730831-84BC-453A-8A40-24C268C4CDEB)] Passing output '' to [Run Script](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.FB3F1227-E1E4-485F-AE7D-090E781D5B39%3EBE99AE6B-5497-4E79-A3E1-0C8AC7AD8EA4)
[15:42:35.411] ERROR: OCR[[Run Script](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.FB3F1227-E1E4-485F-AE7D-090E781D5B39%3EBE99AE6B-5497-4E79-A3E1-0C8AC7AD8EA4)] JIT session error: Symbols not found: [ _OBJC_CLASS_$_NSImage, _OBJC_CLASS_$_NSPasteboard, _NSPasteboardTypeString ]
Failed to materialize symbols: { (main, { _$sSo13VNImageOptionaML, _$sSo16NSPasteboardTypeaABs20_SwiftNewtypeWrapperSCWl, _$s9AlfredOCRAAV8revisionSivau, _$sSo16NSPasteboardTypeaSHSCSH13_rawHashValue4seedS2i_tFTW, _got.$ss35_HasCustomAnyHashableRepresentationP03_tobcD0s0cD0VSgyFTq, _$sSo16NSPasteboardTypeaSHSCSH4hash4intoys6HasherVz_tFTW, _$sSo16NSPasteboardTypeaMB, _$sSo16NSPasteboardTypeaSYSCSY8rawValue03RawD0QzvgTW, _$sSo16NSPasteboardTypeaSYSCSY8rawValuexSg03RawD0Qz_tcfCTW, _$sSo13VNImageOptionaMf, _$sSo13VNImageOptionaMn, _$sSo13VNImageOptionaSYSCSY8rawValue03RawD0QzvgTW, _$sSo16NSPasteboardTypeas35_HasCustomAnyHashableRepresentationSCMc, _associated conformance So13VNImageOptionaSHSCSQ, _$s9AlfredOCRAAV13recognizeText2in8revision0C8Language9languages16recognitionLevel7handlery10Foundation3URLV_SiSbSaySSGSo09VNRequestd11RecognitionJ0VySo0N0C_s5Error_pSgtctFZfA4_, _$sSo13VNImageOptionas21_ObjectiveCBridgeableSCMc, _got.$ss21_ObjectiveCBridgeableP09_bridgeToA1C01_A5CTypeQzyFTq, _$sSo13VNImageOptionaABSHSCWL, _$sSo13VNImageOptionas21_ObjectiveCBridgeableSCMA, _$sSo13VNImageOptionaMB, _$sSaySo27VNRecognizedTextObservationCGSayxGSTsWl, _$sSo16NSPasteboardTypeaMF, _$sSo13VNImageOptionaMF, ___swift_instantiateConcreteTypeFromMangledNameAbstract, _$sSo13VNImageOptionaABs20_SwiftNewtypeWrapperSCWl, _symbolic SaySSG, _$sSo13VNImageOptionaMa, _$sSaySSGSayxGSlsWL, _$s9AlfredOCRAAV13recognizeText2in8revision0C8Language9languages16recognitionLevel7handlery10Foundation3URLV_SiSbSaySSGSo09VNRequestd11RecognitionJ0VySo0N0C_s5Error_pSgtctFZ, _symbolic SaySsG, _$sSo16VNRecognizedTextCML, _$sSaySsGSayxGSlsWL, _$sSo16NSPasteboardTypeas21_ObjectiveCBridgeableSCMA, _$sSo13VNImageOptionaABSQSCWl, _$sSo16NSPasteboardTypeas21_ObjectiveCBridgeableSCMc, _$sSo13VNObservationCML, _associated conformance So16NSPasteboardTypeas20_SwiftNewtypeWrapperSCSY, _$sSo21VNImageRequestHandlerCML, _$sSo13VNImageOptionaSHSCSH13_rawHashValue4seedS2i_tFTW, _$sSo16NSPasteboardTypeaABs35_HasCustomAnyHashableRepresentationSCWL, _$sSo13VNImageOptionaSHSCSH4hash4intoys6HasherVz_tFTW, _$sSo13VNImageOptiona_yptMD, _got.$ss20_SwiftNewtypeWrapperPs35_HasCustomAnyHashableRepresentationTb, _$sSo16NSPasteboardTypeaMa, _$sSo21VNImageRequestHandlerC7cgImage7optionsABSo10CGImageRefa_SDySo0A6OptionaypGtcfcTO, _$sSo9VNRequestCs5Error_pSgIeggg_ABSo7NSErrorCSgIeyByy_TR, _$sSo16NSPasteboardTypeaABs35_HasCustomAnyHashableRepresentationSCWl, _$sSo13VNImageOptionaABs35_HasCustomAnyHashableRepresentationSCWL, _$sSo7NSImageC13byReferencingAB10Foundation3URLV_tcfcTO, _$sSo7NSImageC13byReferencingAB10Foundation3URLV_tcfC, _$sSo7NSImageCML, _$sSo13NSFileManagerC9AlfredOCRE8validates5NeverOSgyF, _$sS2is17FixedWidthIntegersWL, _$sSo13VNImageOptionaSYSCSY8rawValuexSg03RawD0Qz_tcfCTW, __swift_FORCE_LOAD_$_swiftCoreFoundation_$_AlfredOCR, _$sSo13VNImageOptionaABSYSCWl, _$sSaySo27VNRecognizedTextObservationCGMD, _$sSo27VNRecognizedTextObservationCML, _symbolic SaySo16VNRecognizedTextCG, __swift_FORCE_LOAD_$_swiftCoreGraphics_$_AlfredOCR, __swift_FORCE_LOAD_$_swiftUniformTypeIdentifiers_$_AlfredOCR, _$sSaySo16VNRecognizedTextCGSayxGSlsWL, _$sSo16NSPasteboardTypeaSYSCMA, _$sS2Ss21_ObjectiveCBridgeable10FoundationWL, _$sSo16NSPasteboardTypeas20_SwiftNewtypeWrapperSCMc, _$sSo16NSPasteboardTypeas35_HasCustomAnyHashableRepresentationSCsACP03_todeF0s0eF0VSgyFTW, _$sSo13VNImageOptionas20_SwiftNewtypeWrapperSCMc, _symbolic ______ypt So13VNImageOptiona, _$sSo13VNImageOptionas35_HasCustomAnyHashableRepresentationSCMc, _$sSo22VNRecognizeTextRequestCML, _$s9AlfredOCRAAVMa, _symbolic SaySo27VNRecognizedTextObservationCG, __swift_FORCE_LOAD_$_swiftFoundation_$_AlfredOCR, _$sSo16NSPasteboardTypeaSHSCMc, __swift_FORCE_LOAD_$_swiftos_$_AlfredOCR, __swift_FORCE_LOAD_$_swiftOSLog_$_AlfredOCR, _associated conformance So16NSPasteboardTypeaSHSCSQ, _$s9AlfredOCRAAVMn, _associated conformance So13VNImageOptionas20_SwiftNewtypeWrapperSCSY, __swift_FORCE_LOAD_$_swiftCoreImage_$_AlfredOCR, _$sSo16NSPasteboardTypeaABSHSCWL, __swift_FORCE_LOAD_$_swiftObjectiveC_$_AlfredOCR, __swift_FORCE_LOAD_$_swiftCoreMedia_$_AlfredOCR, __swift_FORCE_LOAD_$_swiftMetal_$_AlfredOCR, _$sSaySsGSayxGSlsWl, _got.$s8RawValueSYTl, __swift_FORCE_LOAD_$_swiftCoreAudio_$_AlfredOCR, _$sSaySSGSayxGSlsWl, __swift_FORCE_LOAD_$_swiftCoreML_$_AlfredOCR, __swift_FORCE_LOAD_$_swiftDispatch_$_AlfredOCR, __swift_FORCE_LOAD_$_swiftXPC_$_AlfredOCR, _$sSo13VNImageOptionaABSHSCWl, __swift_FORCE_LOAD_$_swiftIOKit_$_AlfredOCR, __swift_FORCE_LOAD_$_swiftsimd_$_AlfredOCR, _$s9AlfredOCRAAV3runyyFZ, _got.$ss35_HasCustomAnyHashableRepresentationMp, _$sSo16NSPasteboardTypeaMn, _$sSo22VNRecognizeTextRequestC17completionHandlerABySo9VNRequestC_s5Error_pSgtcSg_tcfC, ___swift_allocate_value_buffer, _$sSo16NSPasteboardTypeaABSQSCWL, __swift_FORCE_LOAD_$_swiftQuartzCore_$_AlfredOCR, _$s9AlfredOCRAAV13recognizeText2in8revision0C8Language9languages16recognitionLevel7handlery10Foundation3URLV_SiSbSaySSGSo09VNRequestd11RecognitionJ0VySo0N0C_s5Error_pSgtctFZfA2_, __swift_FORCE_LOAD_$_swiftVision_$_AlfredOCR, _$sSo7NSImageCMa, _$sSo13VNImageOptionaABs20_SwiftNewtypeWrapperSCWL, _$sSo16NSPasteboardTypeaML, _$s10Foundation3URLVSgWOc, _$sSo16NSPasteboardTypeaABs20_SwiftNewtypeWrapperSCWL, _$sSo16NSPasteboardTypeaMf, _got.$ss20_SwiftNewtypeWrapperMp, __swift_FORCE_LOAD_$_swiftDarwin_$_AlfredOCR, _$sSaySo27VNRecognizedTextObservationCGSayxGSTsWL, _got.$ss20_SwiftNewtypeWrapperPSYTb, _$s9AlfredOCRAAV13recognizeText2in8revision0C8Language9languages16recognitionLevel7handlery10Foundation3URLV_SiSbSaySSGSo09VNRequestd11RecognitionJ0VySo0N0C_s5Error_pSgtctFZfA3_, _$sS2is17FixedWidthIntegersWl, _$sSo16NSPasteboardTypeaABSYSCWL, _got.$sSY8rawValuexSg03RawB0Qz_tcfCTq, _got.$ss21_ObjectiveCBridgeableP026_unconditionallyBridgeFromA1Cyx01_A5CTypeQzSgFZTq, _got.$ss21_ObjectiveCBridgeableMp, _$sSaySSGSayxGSKsWl, _symbolic $ss21_ObjectiveCBridgeableP, _symbolic _____ So13VNImageOptiona, _$sSa12_endMutationyyF, ___swift_project_value_buffer, _symbolic _____Sg 10Foundation3URLV, _$sSo13VNImageOptionas21_ObjectiveCBridgeableSCsACP024_conditionallyBridgeFromC1C_6resultSb01_C5CTypeQz_xSgztFZTW, _symbolic _____ So16NSPasteboardTypea, _$sSo9VNRequestCMa, _got.$sSH13_rawHashValue4seedS2i_tFTq, _$sSo13VNImageOptionaSYSCMc, _got.$sSH4hash4intoys6HasherVz_tFTq, _associated conformance So16NSPasteboardTypeas20_SwiftNewtypeWrapperSCs35_HasCustomAnyHashableRepresentation, _$sSo21VNImageRequestHandlerCMa, _got.$s15_ObjectiveCTypes01_A11CBridgeablePTl, _$sSaySo16VNRecognizedTextCGWOh, _$sSaySo16VNRecognizedTextCGSayxGSlsWl, _$s10Foundation3URLVSgWOd, _$sSo27VNRecognizedTextObservationCMa, _$sSo16VNRecognizedTextCMa, _$ss26DefaultStringInterpolationVWOh, _$sSo16NSPasteboardTypeas21_ObjectiveCBridgeableSCsACP024_conditionallyBridgeFromC1C_6resultSb01_C5CTypeQz_xSgztFZTW, _$sSo22VNRecognizeTextRequestCMa, _$s9AlfredOCRAAV9languagesSaySSGvpZ, _$s9AlfredOCRAAV4snap10Foundation3URLVSgvpZ, _$s9AlfredOCRAAV11fileManagerSo06NSFileD0CvpZ, _$s9AlfredOCRAAV11environmentSDyS2SGvpZ, _$sSo13VNObservationCMa, _$sSaySsGWOh, _$sSo16NSPasteboardTypeaABSQSCWl, _$sSJWOh, _$sSo16NSPasteboardTypea8rawValueSSvg, _$sS2sSysWl, _got.$s10Foundation3URLVMn, _$sSaySSGWOh, _got.$sSHMp, _$sSo16NSPasteboardTypea8rawValueABSS_tcfC, _$s6VisionMXM, _$sSo13VNImageOptionas35_HasCustomAnyHashableRepresentationSCsACP03_todeF0s0eF0VSgyFTW, _$s6AppKitMXM, _$s9AlfredOCRAAV8revisionSivpZ, _got.$sSHSQTb, _$sSo13VNImageOptiona8rawValueSSvg, _$sS2Ss21_ObjectiveCBridgeable10FoundationWl, _$sSo16NSPasteboardTypeaABSHSCWl, _$s9AlfredOCRAAV13recognizeText2in8revision0C8Language9languages16recognitionLevel7handlery10Foundation3URLV_SiSbSaySSGSo09VNRequestd11RecognitionJ0VySo0N0C_s5Error_pSgtctFZfA1_, _$s9AlfredOCR4PATHSSvp, _$sSo16NSPasteboardTypeaSQSCSQ2eeoiySbx_xtFZTW, _main, _$sS2SSlsWl, _$sSo16NSPasteboardTypeaSHSCSH9hashValueSivgTW, _$sSSWOh, _$s9AlfredOCRMXM, _$ss5print_9separator10terminatoryypd_S2StFfA0_, _$sSo13VNImageOptiona8rawValueABSS_tcfC, _symbolic So8NSStringC, _$s9AlfredOCRAAV13recognizeText2in8revision0C8Language9languages16recognitionLevel7handlery10Foundation3URLV_SiSbSaySSGSo09VNRequestd11RecognitionJ0VySo0N0C_s5Error_pSgtctFZfA0_, _$sSo16NSPasteboardTypeaABSYSCWl, _$sSo13VNImageOptionaSQSCSQ2eeoiySbx_xtFZTW, _$sSo13VNImageOptionaSHSCSH9hashValueSivgTW, _$s10Foundation3URLVSgMD, _$sSo9VNRequestCML, _$ss27_finalizeUninitializedArrayySayxGABnlF, _$sSo22VNRecognizeTextRequestC17completionHandlerABySo9VNRequestC_s5Error_pSgtcSg_tcfcTO, _$sSaySo16VNRecognizedTextCGMD, _$sSo13VNImageOptionaABSQSCWL, _got.$ss21_ObjectiveCBridgeableP016_forceBridgeFromA1C_6resulty01_A5CTypeQz_xSgztFZTq, _$s9AlfredOCRAAVN, $.AlfredOCR.__inits.0, _$ss5print_9separator10terminatoryypd_S2StFfA1_, _$sSo13VNImageOptionaSYSCMA, _$sS2sSysWL, _$sSo13VNImageOptionaABs35_HasCustomAnyHashableRepresentationSCWl, _$s9AlfredOCRAAV11environmentSDyS2SGvau, _$sSaySSGSayxGSKsWL, _symbolic $sSY, _got.$sSYMp, ___swift_instantiateConcreteTypeFromMangledName, _got.$sSQMp, _symbolic SS, _$s9AlfredOCRAAV9languagesSaySSGvau, _$sSaySsGMD, _$sSo13VNImageOptionaSHSCMc, _$s9AlfredOCRAAV11fileManagerSo06NSFileD0Cvau, _$sSaySSGMD, _got.$sSY8rawValue03RawB0QzvgTq, _got.$ss21_ObjectiveCBridgeableP024_conditionallyBridgeFromA1C_6resultSb01_A5CTypeQz_xSgztFZTq, _$s9AlfredOCRAAV4snap10Foundation3URLVSgvau, _$sSoMXM, _symbolic _____ 9AlfredOCRAAV, _got.$sSQ2eeoiySbx_xtFZTq, _$sSo13VNImageOptionas21_ObjectiveCBridgeableSCsACP016_forceBridgeFromC1C_6resulty01_C5CTypeQz_xSgztFZTW, _$sSo21VNImageRequestHandlerC7cgImage7optionsABSo10CGImageRefa_SDySo0A6OptionaypGtcfC, _$sS2SSlsWL, _got.$sSH9hashValueSivgTq, _$sSo13VNImageOptionas21_ObjectiveCBridgeableSCsACP09_bridgeToC1C01_C5CTypeQzyFTW, _$sSlsSQ7ElementRpzrlE5split9separator9maxSplits25omittingEmptySubsequencesSay11SubSequenceQzGAB_SiSbtFfA1_, _$sSlsSQ7ElementRpzrlE5split9separator9maxSplits25omittingEmptySubsequencesSay11SubSequenceQzGAB_SiSbtFfA0_, _$sSo16NSPasteboardTypeaSQSCMc, _$sSo16NSPasteboardTypeas21_ObjectiveCBridgeableSCsACP09_bridgeToC1C01_C5CTypeQzyFTW, _$s10Foundation3URLV8filePath13directoryHint10relativeToACSS_AC09DirectoryF0OACSgtcfcfA0_, _$sSo13VNImageOptionaABSYSCWL, _$sSo16NSPasteboardTypeaSYSCMc, _associated conformance So13VNImageOptionas20_SwiftNewtypeWrapperSCs35_HasCustomAnyHashableRepresentation, _$sSo16NSPasteboardTypeas21_ObjectiveCBridgeableSCsACP026_unconditionallyBridgeFromC1Cyx01_C5CTypeQzSgFZTW, _$sSo16NSPasteboardTypeas21_ObjectiveCBridgeableSCsACP016_forceBridgeFromC1C_6resulty01_C5CTypeQz_xSgztFZTW, _$sSo13VNImageOptionaSQSCMc, _$sSo13VNImageOptionas21_ObjectiveCBridgeableSCsACP026_unconditionallyBridgeFromC1Cyx01_C5CTypeQzSgFZTW }) }
[15:42:35.431] OCR[[Run Script](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.FB3F1227-E1E4-485F-AE7D-090E781D5B39%3EBE99AE6B-5497-4E79-A3E1-0C8AC7AD8EA4)] Processing complete
[15:42:35.435] OCR[[Run Script](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.FB3F1227-E1E4-485F-AE7D-090E781D5B39%3EBE99AE6B-5497-4E79-A3E1-0C8AC7AD8EA4)] Passing output '' to [Conditional](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.FB3F1227-E1E4-485F-AE7D-090E781D5B39%3EC568EB21-F3AD-4A52-86E2-D4AFA3573DCE)
[15:42:35.436] OCR[[Conditional](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.FB3F1227-E1E4-485F-AE7D-090E781D5B39%3EC568EB21-F3AD-4A52-86E2-D4AFA3573DCE)] Processing complete
[15:42:35.437] OCR[[Conditional](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.FB3F1227-E1E4-485F-AE7D-090E781D5B39%3EC568EB21-F3AD-4A52-86E2-D4AFA3573DCE)] Passing output '' to [Post Notification](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.FB3F1227-E1E4-485F-AE7D-090E781D5B39%3E8278A76A-BFA3-41CC-A313-0EF753D17D9B)

**Comment by zeitlings** [comment]
[OCR Light v1.2.0](https://github.com/zeitlings/alfred-workflows/releases/tag/v1.2.0-ocr)
