### ISSUE TITLE
OCR workflow

### ISSUE THREAD

**Issue by JJJJJJJJJJl** [zeitlings/alfred-workflows#9]
First, It's a literally nice workflow 🙂
Thanks

Anyway, there's some issues on workflow

I tried to use workflow on Korean and Japanese. But both of them do not work even I add 'Languages' on 'configure workflow' section.

Can you check it please?

Have a nice day.

**Comment by JJJJJJJJJJl** [comment]
<img width="1448" alt="스크린샷 2023-11-14 오후 11 37 53" src="https://github.com/zeitlings/alfred-workflows/assets/104782507/d817d970-8e24-4888-8b3f-509482df5d0b">

**Comment by zeitlings** [comment]
Hey, I just tested it and it worked fine for me. Try moving Korean up in the list: `ko-KR, en-US, de-DE, fr-FR`

**Comment by JJJJJJJJJJl** [comment]
Thanks for your help.

It works after moving korean up in the list :)

Have a nice day
